services:
  object-storage:
    image: quay.io/minio/minio:RELEASE.2025-07-23T15-54-02Z
    environment:
      MINIO_ROOT_USER: ${OBJECT_STORAGE_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${OBJECT_STORAGE_SECRET_ACCESS_KEY}
      MINIO_ACCESS_KEY: ${OBJECT_STORAGE_ACCESS_KEY_ID}
      MINIO_SECRET_KEY: ${OBJECT_STORAGE_SECRET_ACCESS_KEY}
    entrypoint: sh
    ports:
      - "9000:9000"
      - "9001:9001"
    command: -c 'mkdir -p /data/${OBJECT_STORAGE_BUCKET} && /usr/bin/minio server --console-address ":9001" /data'
    volumes:
      - object-storage:/data
volumes:
  object-storage:
