[tools]
elixir = "1.18.4-otp-28"
erlang = "28.0.2"

[env]
OBJECT_STORAGE_BASE_URL = "http://localhost:9000"
OBJECT_STORAGE_ACCESS_KEY_ID = "minio"
OBJECT_STORAGE_SECRET_ACCESS_KEY = "minio123"
OBJECT_STORAGE_BUCKET = "avelo"
UPDATE_INTERVAL_SECONDS = 60
