[tools]
elixir = "1.18.4-otp-28"
erlang = "28.0.2"

[env]
AWS_ENDPOINT_URL_S3 = "http://localhost:9000"
AWS_ACCESS_KEY_ID = "minio"
AWS_SECRET_ACCESS_KEY = "minio123"
BUCKET_NAME = "avelo"
UPDATE_INTERVAL_SECONDS = 60
